# Generated by Django 3.0.5 on 2021-05-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraCol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turnover', models.CharField(max_length=100, verbose_name='turnover')),
                ('market_capitalization', models.CharField(max_length=100, verbose_name='market capitalization')),
            ],
        ),
    ]
